export const ERR_PREFIX = '@ERR:'

export const ErrorCode = {
  OPERATION_FAILED: 'OPERATION_FAILED',
  VAULT_LOCKED: 'VAULT_LOCKED',
  VAULT_UNLOCK_REQUIRED: 'VAULT_UNLOCK_REQUIRED',
  DATABASE_NOT_INITIALIZED: 'DATABASE_NOT_INITIALIZED',
  MASTER_PASSWORD_TOO_SHORT: 'MASTER_PASSWORD_TOO_SHORT',
  MASTER_PASSWORD_MISMATCH: 'MASTER_PASSWORD_MISMATCH',
  VAULT_ALREADY_INITIALIZED: 'VAULT_ALREADY_INITIALIZED',
  MASTER_PASSWORD_NOT_CREATED: 'MASTER_PASSWORD_NOT_CREATED',
  WRONG_MASTER_PASSWORD: 'WRONG_MASTER_PASSWORD',
  ENTRY_CREATE_FAILED: 'ENTRY_CREATE_FAILED',
  ENTRY_NOT_FOUND: 'ENTRY_NOT_FOUND',
  ENTRY_UPDATE_FAILED: 'ENTRY_UPDATE_FAILED',
  FAVORITE_UPDATE_FAILED: 'FAVORITE_UPDATE_FAILED',
  CATEGORY_NAME_EMPTY: 'CATEGORY_NAME_EMPTY',
  CATEGORY_NAME_TOO_LONG: 'CATEGORY_NAME_TOO_LONG',
  CATEGORY_NAME_RESERVED: 'CATEGORY_NAME_RESERVED',
  CATEGORY_NAME_EXISTS: 'CATEGORY_NAME_EXISTS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_ENTRIES: 'CATEGORY_HAS_ENTRIES',
  CATEGORY_MIN_ONE: 'CATEGORY_MIN_ONE',
  CATEGORY_LIST_INCOMPLETE: 'CATEGORY_LIST_INCOMPLETE',
  RECOVERY_KEY_INVALID_FORMAT: 'RECOVERY_KEY_INVALID_FORMAT',
  RECOVERY_KEY_NOT_SET: 'RECOVERY_KEY_NOT_SET',
  MASTER_PASSWORD_NOT_SET: 'MASTER_PASSWORD_NOT_SET',
  MASTER_PASSWORD_INCORRECT: 'MASTER_PASSWORD_INCORRECT',
  RESET_REQUIRES_LOCKED: 'RESET_REQUIRES_LOCKED',
  RECOVERY_NOT_CONFIGURED: 'RECOVERY_NOT_CONFIGURED',
  RECOVERY_KEY_INVALID: 'RECOVERY_KEY_INVALID',
  TITLE_REQUIRED: 'TITLE_REQUIRED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  DEFAULT_CATEGORY_NOT_FOUND: 'DEFAULT_CATEGORY_NOT_FOUND',
} as const

export type ErrorCodeKey = (typeof ErrorCode)[keyof typeof ErrorCode]

export function appError(code: ErrorCodeKey, params?: Record<string, string | number>): Error {
  if (params && Object.keys(params).length > 0) {
    return new Error(`${ERR_PREFIX}${code}:${JSON.stringify(params)}`)
  }
  return new Error(`${ERR_PREFIX}${code}`)
}
