import type { ProductTourDefinition } from '@/shared/productTourTypes'

export const PRODUCT_TOURS: ProductTourDefinition[] = [
  {
    id: 'intro',
    titleKey: 'productTour.tours.intro.title',
    descKey: 'productTour.tours.intro.desc',
    durationKey: 'productTour.tours.intro.duration',
    icon: 'compass',
    accent: 'var(--accent-primary)',
    requiresUnlock: true,
    steps: [
      {
        id: 'welcome',
        target: '',
        titleKey: 'productTour.steps.intro.welcome.title',
        bodyKey: 'productTour.steps.intro.welcome.body',
        placement: 'center',
      },
      {
        id: 'layout',
        target: '[data-tour="vault-layout"]',
        titleKey: 'productTour.steps.intro.layout.title',
        bodyKey: 'productTour.steps.intro.layout.body',
        highlight: 'columns',
        cardPlacement: 'center',
        screen: 'vault',
      },
      {
        id: 'categories',
        target: '[data-tour="sidebar-categories"]',
        titleKey: 'productTour.steps.intro.categories.title',
        bodyKey: 'productTour.steps.intro.categories.body',
        placement: 'right',
        screen: 'vault',
        padding: 8,
      },
      {
        id: 'list',
        target: '[data-tour="list-toolbar"]',
        titleKey: 'productTour.steps.intro.list.title',
        bodyKey: 'productTour.steps.intro.list.body',
        placement: 'bottom',
        screen: 'vault',
        padding: 10,
      },
    ],
  },
  {
    id: 'organize',
    titleKey: 'productTour.tours.organize.title',
    descKey: 'productTour.tours.organize.desc',
    durationKey: 'productTour.tours.organize.duration',
    icon: 'folder',
    accent: '#6b9bd1',
    requiresUnlock: true,
    steps: [
      {
        id: 'categories',
        target: '[data-tour="sidebar-categories"]',
        titleKey: 'productTour.steps.organize.categories.title',
        bodyKey: 'productTour.steps.organize.categories.body',
        placement: 'right',
        screen: 'vault',
      },
      {
        id: 'tag-filter',
        target: '[data-tour="list-tag-filter-panel"]',
        fallbackTarget: '[data-tour="list-toolbar"]',
        titleKey: 'productTour.steps.organize.tagFilter.title',
        bodyKey: 'productTour.steps.organize.tagFilter.body',
        placement: 'bottom',
        cardPlacement: 'bottom',
        screen: 'vault',
        prepare: ['collapse-footer-menus', 'expand-tag-filter'],
        padding: 6,
      },
      {
        id: 'new-category',
        target: '[data-tour="sidebar-new-category"]',
        titleKey: 'productTour.steps.organize.newCategory.title',
        bodyKey: 'productTour.steps.organize.newCategory.body',
        placement: 'bottom',
        screen: 'vault',
        prepare: ['collapse-list-menus'],
      },
      {
        id: 'utilities',
        target: '[data-tour="sidebar-utilities"]',
        titleKey: 'productTour.steps.organize.utilities.title',
        bodyKey: 'productTour.steps.organize.utilities.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['collapse-footer-menus'],
      },
    ],
  },
  {
    id: 'entries',
    titleKey: 'productTour.tours.entries.title',
    descKey: 'productTour.tours.entries.desc',
    durationKey: 'productTour.tours.entries.duration',
    icon: 'key',
    accent: '#c9a227',
    requiresUnlock: true,
    steps: [
      {
        id: 'search',
        target: '[data-tour="list-search"]',
        titleKey: 'productTour.steps.entries.search.title',
        bodyKey: 'productTour.steps.entries.search.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'sort-layout',
        target: '[data-tour="list-actions"]',
        titleKey: 'productTour.steps.entries.sortLayout.title',
        bodyKey: 'productTour.steps.entries.sortLayout.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'new-entry',
        target: '[data-tour="list-new-entry"]',
        titleKey: 'productTour.steps.entries.newEntry.title',
        bodyKey: 'productTour.steps.entries.newEntry.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'detail',
        target: '[data-tour="detail-panel"]',
        fallbackTarget: '[data-tour="list-new-entry"]',
        titleKey: 'productTour.steps.entries.detail.title',
        bodyKey: 'productTour.steps.entries.detail.body',
        placement: 'left',
        screen: 'vault',
        prepare: ['expand-detail', 'select-first-entry'],
        padding: 10,
      },
    ],
  },
  {
    id: 'tools',
    titleKey: 'productTour.tours.tools.title',
    descKey: 'productTour.tours.tools.desc',
    durationKey: 'productTour.tours.tools.duration',
    icon: 'wrench',
    accent: '#7ec8a4',
    requiresUnlock: true,
    steps: [
      {
        id: 'utilities',
        target: '[data-tour="sidebar-toolbox"]',
        titleKey: 'productTour.steps.tools.utilities.title',
        bodyKey: 'productTour.steps.tools.utilities.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['collapse-footer-menus'],
      },
      {
        id: 'password-gen',
        target: '[data-tour="tool-password-gen"]',
        fallbackTarget: '[data-tour="sidebar-toolbox-panel"]',
        titleKey: 'productTour.steps.tools.passwordGen.title',
        bodyKey: 'productTour.steps.tools.passwordGen.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['expand-toolbox'],
        padding: 6,
      },
      {
        id: 'password-health',
        target: '[data-tour="tool-password-health"]',
        fallbackTarget: '[data-tour="sidebar-toolbox-panel"]',
        titleKey: 'productTour.steps.tools.passwordHealth.title',
        bodyKey: 'productTour.steps.tools.passwordHealth.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['expand-toolbox'],
        padding: 6,
      },
      {
        id: 'clipboard',
        target: '[data-tour="tool-clipboard"]',
        fallbackTarget: '[data-tour="sidebar-toolbox-panel"]',
        titleKey: 'productTour.steps.tools.clipboard.title',
        bodyKey: 'productTour.steps.tools.clipboard.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['expand-toolbox'],
        padding: 6,
      },
      {
        id: 'trash',
        target: '[data-tour="tool-trash"]',
        titleKey: 'productTour.steps.tools.trash.title',
        bodyKey: 'productTour.steps.tools.trash.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['collapse-footer-menus'],
      },
    ],
  },
  {
    id: 'titlebar',
    titleKey: 'productTour.tours.titlebar.title',
    descKey: 'productTour.tours.titlebar.desc',
    durationKey: 'productTour.tours.titlebar.duration',
    icon: 'panel-top',
    accent: '#a78bfa',
    requiresUnlock: true,
    steps: [
      {
        id: 'skin',
        target: '[data-tour="titlebar-skin"]',
        titleKey: 'productTour.steps.titlebar.skin.title',
        bodyKey: 'productTour.steps.titlebar.skin.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'lock',
        target: '[data-tour="titlebar-lock"]',
        titleKey: 'productTour.steps.titlebar.lock.title',
        bodyKey: 'productTour.steps.titlebar.lock.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'clipboard',
        target: '[data-tour="titlebar-clipboard"]',
        titleKey: 'productTour.steps.titlebar.clipboard.title',
        bodyKey: 'productTour.steps.titlebar.clipboard.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'pin',
        target: '[data-tour="titlebar-pin"]',
        titleKey: 'productTour.steps.titlebar.pin.title',
        bodyKey: 'productTour.steps.titlebar.pin.body',
        placement: 'bottom',
        screen: 'vault',
      },
      {
        id: 'learn',
        target: '[data-tour="titlebar-learn"]',
        titleKey: 'productTour.steps.titlebar.learn.title',
        bodyKey: 'productTour.steps.titlebar.learn.body',
        placement: 'bottom',
        screen: 'vault',
      },
    ],
  },
  {
    id: 'settings',
    titleKey: 'productTour.tours.settings.title',
    descKey: 'productTour.tours.settings.desc',
    durationKey: 'productTour.tours.settings.duration',
    icon: 'settings',
    accent: '#f07178',
    requiresUnlock: true,
    steps: [
      {
        id: 'open',
        target: '[data-tour="sidebar-settings"]',
        titleKey: 'productTour.steps.settings.open.title',
        bodyKey: 'productTour.steps.settings.open.body',
        placement: 'top',
        cardPlacement: 'top',
        screen: 'vault',
        prepare: ['collapse-footer-menus'],
      },
      {
        id: 'nav',
        target: '[data-tour="settings-nav"]',
        titleKey: 'productTour.steps.settings.nav.title',
        bodyKey: 'productTour.steps.settings.nav.body',
        placement: 'right',
        screen: 'settings',
        padding: 8,
      },
      {
        id: 'security',
        target: '[data-tour="settings-security"]',
        titleKey: 'productTour.steps.settings.security.title',
        bodyKey: 'productTour.steps.settings.security.body',
        placement: 'bottom',
        screen: 'settings',
        settingsTab: 'security',
      },
      {
        id: 'clipboard',
        target: '[data-tour="settings-clipboard"]',
        titleKey: 'productTour.steps.settings.clipboard.title',
        bodyKey: 'productTour.steps.settings.clipboard.body',
        placement: 'bottom',
        screen: 'settings',
        settingsTab: 'clipboard',
      },
      {
        id: 'browser',
        target: '[data-tour="settings-browser"]',
        titleKey: 'productTour.steps.settings.browser.title',
        bodyKey: 'productTour.steps.settings.browser.body',
        placement: 'bottom',
        screen: 'settings',
        settingsTab: 'browser',
      },
      {
        id: 'quickbar',
        target: '[data-tour="settings-quickbar"]',
        titleKey: 'productTour.steps.settings.quickbar.title',
        bodyKey: 'productTour.steps.settings.quickbar.body',
        placement: 'bottom',
        screen: 'settings',
        settingsTab: 'quickbar',
      },
      {
        id: 'trash',
        target: '[data-tour="settings-trash"]',
        titleKey: 'productTour.steps.settings.trash.title',
        bodyKey: 'productTour.steps.settings.trash.body',
        placement: 'bottom',
        screen: 'settings',
        settingsTab: 'trash',
      },
      {
        id: 'data',
        target: '[data-tour="settings-data"]',
        titleKey: 'productTour.steps.settings.data.title',
        bodyKey: 'productTour.steps.settings.data.body',
        placement: 'bottom',
        screen: 'settings',
        settingsTab: 'data',
      },
    ],
  },
]

export function getTourById(id: string): ProductTourDefinition | undefined {
  return PRODUCT_TOURS.find((t) => t.id === id)
}
